### ISSUE TITLE
Can someone help me to start the bot?

### ISSUE THREAD

**Issue by raducutv** [mrtolkien/inhouse_bot#10]
Hi
I would appreciate if anyone can help me install it on me. (Put the token on him.) I tried to follow this steps:
Installation
- git clone https://github.com/mrtolkien/inhouse_bot.git
- cd inhouse_bot
- pipenv install
- pipenv run python run_bot.py
 but I can't.

But I always get this error:

![image](https://user-images.githubusercontent.com/74502317/99290156-31971380-283e-11eb-95ee-e34e2f0bee17.png)

Thank you!

ps. Sorry but I don't know where to ask these things.

**Comment by mrtolkien** [comment]
I’ll write a new tutorial soon
