### ISSUE TITLE
[Suggestion] Ingame role

### ISSUE THREAD

**Issue by pedrofracassi** [mrtolkien/inhouse_bot#14]
We're using the bot for inhouses with players from the tier 3 leagues from Brazil. Sometimes, people want to listen to the player's comms, but forget to mute their mics.

A solution I thought of would be to have a role that is assigned to people currently in games, and that role would have permission to talk in the game channels.

Other use cases probably exist, like revealing game channels only to those playing, etc.

**Comment by mrtolkien** [comment]
Definitely sounds like a nice-to-have feature, especially if it could create two voice channels per game and give blue/right permissions.

Unfortunately I won’t have time to develop it, but I’ll welcome any pull requests that’s backwards compatible and includes it!

**Comment by pedrofracassi** [comment]
I ended up writing something that creates channels automatically. Not that fluent in Python, so I implemented some extras in JavaScript with a secondary bot that reads messages by the main one: https://github.com/pedrofracassi/inhouse-bot-extras
