### ISSUE TITLE
Problem with setting the Command Prefix

### ISSUE THREAD

**Issue by LilRiceball** [mrtolkien/inhouse_bot#15]
Hey there, I tried following the instructions you've given but I seem to be having trouble setting the command prefix. 
![image](https://user-images.githubusercontent.com/46391291/103259659-59fb4d00-4968-11eb-8dd6-ec629c28c371.png)
In this image the two commented lines are what I've tried as well as INHOUSE_BOT_COMMAND_PREFIX = "&" and INHOUSE_BOT_COMMAND_PREFIX = & to try to set the prefix to &, but all of them didn't seem to do the trick so I would greatly appreciate a bit more help on setting the changed prefix

**Comment by mrtolkien** [comment]
I didn’t push a Docker image with that feature indeed!

I’m having internet trouble and haven’t set up an automated build so I’ll try to do it tomorrow.

**Comment by LilRiceball** [comment]
Much appreciated! I look forward to it very much haha.

**Comment by mrtolkien** [comment]
Pushed a new image with Python 3.9 and the latest changes, should be good to go.
