### ISSUE TITLE
Duo command ain't working

### ISSUE THREAD

**Issue by victorcstv** [mrtolkien/inhouse_bot#18]
I have tested a many times the command to play duo queue but ain't working in my server.
"!queue adc @otherplayer sup"

![image](https://user-images.githubusercontent.com/62709537/103973752-fd114b00-514e-11eb-82ab-58c8886a41e0.png)

![image](https://user-images.githubusercontent.com/62709537/103973783-10241b00-514f-11eb-9b49-956fad864c91.png)

Could this be a bug or is it really not working?

**Comment by OliveiraCleidson** [comment]
In my container is working fine, have you updated your container after the Jan 1st update?

**Comment by victorcstv** [comment]
> In my container is working fine, have you updated your container after the Jan 1st update? 

How I do it without remove the current container?

**Comment by mrtolkien** [comment]
You can’t, but it shouldn’t be an issue since all the data is in the postgres database
