### ISSUE TITLE
!Ranking Leaderboard 0 games

### ISSUE THREAD

**Issue by inerogg** [mrtolkien/inhouse_bot#2]
We're getting values for people with 0 games played. Is there any way to make it a requirement that someone has at least 1 game played before they're put onto a leaderboard?

![fc0b36bde13b38942804441a5180485c](https://user-images.githubusercontent.com/65264865/81761939-2ecaf880-9480-11ea-8bfc-5ce26d4fd371.png)

**Comment by mrtolkien** [comment]
Resolved in the last commit! Will require a bot restart to be deployed.
