### ISSUE TITLE
10 Players in Queue but games not found

### ISSUE THREAD

**Issue by hkoleoso911** [mrtolkien/inhouse_bot#20]
When I get 10 people to queue up, the bot doesn't seem to do anything past that. I was expecting a "queue pop" and players will be able to accept from there?

![image](https://user-images.githubusercontent.com/38491984/108384356-94fc5d00-7202-11eb-9abe-218c29a47051.png)

![image](https://user-images.githubusercontent.com/38491984/108384381-9af23e00-7202-11eb-9160-a9a4360e9b39.png)

Currently trying to figure out where exactly to put the `INHOUSE_BOT_TEST=1` environment variable but having trouble. Would it need to go in the docker-compose.yml as well? I've tried env file as well and it doesn't seem to be working. 

![image](https://user-images.githubusercontent.com/38491984/108384794-fae8e480-7202-11eb-9ed8-60a505bf3841.png)

**Comment by mrtolkien** [comment]
Looking at your screenshot they are queuing in two different queues. There is one queue per channel.
