### ISSUE TITLE
Question with ranking

### ISSUE THREAD

**Issue by dragonblaze27** [mrtolkien/inhouse_bot#28]
Is there a way to have more than 100 pearson on the command !ranking? And btw, i'm having a lot of problems with the database, i can't access it, i thought the password and the nick are the one i modify in the docker compose but what about the others settings the other credential it ask? Like server and database?

**Comment by mrtolkien** [comment]
> Is there a way to have more than 100 pearson on the command !ranking?

Not at the moment

> Like server

Depends how you're running it!

> and database

`inhouse_bot`
