### ISSUE TITLE
others db access problems

### ISSUE THREAD

**Issue by dragonblaze27** [mrtolkien/inhouse_bot#29]
![image](https://user-images.githubusercontent.com/86256111/125252848-1c08b980-e2f9-11eb-8b43-8cb7cb0295de.png)
i'm having this problem and i don't know what is the problem, is there an other way to access to the database (maybe because is runned locally it exist? idk)

**Comment by mrtolkien** [comment]
The project's issues is not your own debugger. This has absolutely nothing to do with this project but with adminer, postgres, and docker.
