### ISSUE TITLE
Completly clueless about Python but would like to use the bot on my server.

### ISSUE THREAD

**Issue by gMithos** [mrtolkien/inhouse_bot#3]
So I've made some quick research on python and I cant get to install your bot on my discord. Followed every steps in the installation section but when I get to pipenv run python run_bot.py it shows me this: https://paste.pythondiscord.com/itopuqobud.py . What am I missing? I'm thinking I should put something else than just my bot token in the run_bot file. Thanks !

**Comment by mrtolkien** [comment]
There’s an issue in my other module `lol_id_tools` that I’m fixing atm, and will update the bot accordingly when it’s done.

**Comment by gMithos** [comment]
Parfait :) . Just close the issue when it's done to let me know. Et encore meric :))

**Comment by mrtolkien** [comment]
Done.
