### ISSUE TITLE
!queue command emoji error ( HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji )

### ISSUE THREAD

**Issue by firasjaber** [mrtolkien/inhouse_bot#8]
I am getting an error on command '!queue role' and I think it's related to the emoji code. here a screenshot of the error on discord 
 & logs
ps: I think other commands are working fine but can't really test them because I need to queue in order to have games data etc

![dicord-error-message](https://user-images.githubusercontent.com/41070156/98718716-15532c80-238f-11eb-875a-f27d49f8d61c.PNG)
![docker-error-message](https://user-images.githubusercontent.com/41070156/98718722-171cf000-238f-11eb-9c1f-78919da388e1.PNG)

**Comment by firasjaber** [comment]
Do I have to add specific channels to the discord server in the order for it to work? , sorry if this is a dumb question but I cant find anything related to this on the readme file

**Comment by mrtolkien** [comment]
The current version does not work anymore as I’m working on a few changes. Please wait around 10 days and I’ll have a new version up and running.

Sorry for not branching it properly at first (it is now on the refactor branch).

**Comment by mrtolkien** [comment]
I’ll leave the issue open until the fix/new version is out.

**Comment by mrtolkien** [comment]
Video tutorial + written tutorial + demo gif done:
https://twitter.com/TolkiCasts/status/1328972072677122049

Now *please* raise issues if there are bugs, as there 100% will be with this full rework!
