### ISSUE TITLE
ImportError: cannot import name 'game_queue' from partially initialized module 'inhouse_bot'

### ISSUE THREAD

**Issue by raducutv** [mrtolkien/inhouse_bot#9]
![image](https://user-images.githubusercontent.com/74502317/99190156-48b60280-2765-11eb-8f32-56546f6cf829.png)

Can you help me please with this error?

Thank you!

**Comment by mrtolkien** [comment]
Not really, the current repo is not a stable/release version and should not be used as such. You can look at older versions if you prefer, but the best thing is just to wait imo.
